title: YuhaoWang's Homepage
page-top-title: YuhaoWang
top-section-bg-text: Welcome to my homepage
home-subtitle: YuhaoWang&ensp;|&ensp;王宇豪
copyright-text: '&copy; YuhaoWang 2023-2025. All Rights Reserved.'
